// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SANTHOSHEFLibrary;

namespace SANTHOSHEFLibrary.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20240620094718_District")]
    partial class District
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SANTHOSHEFLibrary.ConstituteDetails", b =>
                {
                    b.Property<long>("ConstituteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("ConstitueName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<long>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalNoOfFemaleVoters")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalNoOfMaleVoters")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalNumberOfVoters")
                        .HasColumnType("bigint");

                    b.HasKey("ConstituteID");

                    b.ToTable("ConstituteDetailsEF");
                });

            modelBuilder.Entity("SANTHOSHEFLibrary.Entity.District", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("ConstituteDetailsConstituteID")
                        .HasColumnType("bigint");

                    b.Property<string>("Districtname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConstituteDetailsConstituteID");

                    b.ToTable("DistrictsEF");
                });

            modelBuilder.Entity("SANTHOSHEFLibrary.Entity.District", b =>
                {
                    b.HasOne("SANTHOSHEFLibrary.ConstituteDetails", null)
                        .WithMany("District")
                        .HasForeignKey("ConstituteDetailsConstituteID");
                });

            modelBuilder.Entity("SANTHOSHEFLibrary.ConstituteDetails", b =>
                {
                    b.Navigation("District");
                });
#pragma warning restore 612, 618
        }
    }
}
